# Generated by Django 4.1.7 on 2023-05-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercodehistory",
            name="lang",
            field=models.CharField(default="python", max_length=50),
        ),
    ]
