# Generated by Django 4.1.7 on 2023-06-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_usercodehistory_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="code",
            field=models.TextField(default=""),
        ),
    ]
