# Generated by Django 4.1.7 on 2023-06-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_submission_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemRecommend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problem",
                    ),
                ),
            ],
        ),
    ]
