# Generated by Django 4.1.7 on 2023-06-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_submission_code"),
        ("codes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="history",
        ),
        migrations.RemoveField(
            model_name="deadcode",
            name="history",
        ),
        migrations.RemoveField(
            model_name="refactor",
            name="history",
        ),
        migrations.RemoveField(
            model_name="review",
            name="history",
        ),
        migrations.AddField(
            model_name="comment",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.submission",
            ),
        ),
        migrations.AddField(
            model_name="deadcode",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.submission",
            ),
        ),
        migrations.AddField(
            model_name="refactor",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.submission",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.submission",
            ),
        ),
    ]
