# Generated by Django 4.1.7 on 2023-06-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
