export { default as Home } from './HomePage'
export { default as Auth } from './AuthPage'
export { default as Profile } from './ProfilePage'
export { default as Problem } from './ProblemPage'
export { default as Notice} from './NoticePage'
export { default as Questions} from './QuestionsPage'
