# Generated by Django 4.1.7 on 2023-06-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureRecommend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.lecture",
                    ),
                ),
            ],
        ),
    ]
