# Generated by Django 4.1.7 on 2023-06-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_lecturerecommend"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="memo",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="LectureComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.lecture",
                    ),
                ),
            ],
        ),
    ]
