# Generated by Django 4.1.7 on 2023-06-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0003_lecture_memo_lecturecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerecommend",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
