# Generated by Django 4.1.7 on 2023-06-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_lecturerecommend_update_at'),
        ('lectures', '0005_alter_lecture_memo'),
    ]

    operations = [
    ]
