# Generated by Django 4.1.7 on 2023-05-25 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(default='', max_length=50)),
                ('github_username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_image_url', models.URLField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
