# Generated by Django 4.1.7 on 2023-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_active_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGitHubRepository",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("repo_name", models.CharField(max_length=128)),
                ("lang", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("topics", models.TextField(blank=True, null=True)),
                ("memo", models.TextField(blank=True, default="", null=True)),
            ],
        ),
    ]
