# Generated by Django 4.1.7 on 2023-06-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_usergithubrepository"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergithubrepository",
            name="github_username",
            field=models.CharField(
                db_index=True, default="", max_length=50, unique=True
            ),
        ),
    ]
