# Generated by Django 4.1.7 on 2023-06-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_usergithubrepository_github_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergithubrepository",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
